train_settings:
  lr: !!float 0.001
  optimizer: Adam
  dataset: deepfashion256
  model: Base
  epochs: !!int 32
  isTrain: TRUE
  load_size: 256
  fine_size: 256
  refresh: TRUE
  batchSize: 32

test_settings:
  inference: TRUE