train_settings:
    lr: !!float 0.001
    optimizer: Adam
    dataset: deepfashion256
    model: CTPS
    epochs: !!int 32
    isTrain: TRUE
    load_size: 256
    fine_size: 256
    refresh: TRUE
    batchSize: 2
    dropout_rate: 0.5
    hidden: 16
    beta1: 0.1
    lr_policy: plateau
    grid_size: 3
    semantic: 20
    keypoint: 18
    pyramid_num: 2
    loss:
        gan_loss: [0.0, MSE]
        l1_loss: [1.0, L1]
        nn_loss: [0.01, NNL]
        iou_loss: [-1.0, IOU]
test_settings:
    inference: TRUE