train_settings:
    lr: !!float 1.5e-4
    optimizer: Adam
    dataset: close_btn
    resize_or_crop: resize_and_crop
    model: YOLO
    epochs: !!int 100
    isTrain: TRUE
    load_size: 416
    fine_size: 416
    refresh: TRUE
    batchSize: 16
    beta1: 0.5
    lr_policy: plateau
    latent_dim: 100
    loss:
        bce_loss: [1.0, BCE]
        nn_loss: [0.01, NNL]
        mse_loss: [0.5, MSE]
        gan_bce_loss: [5.0, BCE]
        w_loss: [1.0, WST]

test_settings:
    inference: TRUE